In [ ]:
# Integer
x = 10
print(type(x))


In [ ]:
# Float
y = 10.0
print(type(y))


In [ ]:
# String
z = "Hello, World!"
print(type(z))


In [ ]:
# Boolean
a = True
print(type(a))


#### Arithmetic Operations

Python supports all the basic arithmetic operations.

In [ ]:
# Addition
print(5 + 5)

In [ ]:
# Subtraction
print(5 - 2)


In [ ]:
# Multiplication
print(3 * 3)


In [ ]:
# Division
print(10 / 2)


In [ ]:
# Exponentiation
print(4 ** 2)

In [ ]:
print(10 // 3)

#### Logical Operations

Python also supports logical operations, which are often used in conditional statements.

In [ ]:
# And operation
print(True and False)


In [ ]:
# Or operation
print(True or False)


In [ ]:
# Not operation
print(not True)

#### Conditional Statements

Conditional statements are used to perform different computations or actions depending on whether a condition evaluates to true or false.

In [ ]:
# Define a variable
x = 10

# If statement
if x > 0:
    print("x is positive")


In [ ]:
# If-else statement
if x % 2 == 0:
    print("x is even")
else:
    print("x is odd")


In [ ]:
# If-elif-else statement
if x < 0:
    print("x is negative")
elif x == 0:
    print("x is zero")
else:
    print("x is positive")

#### Loops

Loops are used to repeatedly execute a block of code.


In [ ]:
# For loop
for i in range(5):
    print(i)


In [ ]:
# While loop
i = 0
while i < 5:
    print(i)
    i += 1


In [ ]:
# Loop through a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

#### Functions

Functions are reusable blocks of code that perform a specific task.

In [ ]:
# Define a function
def greet(name):
      return "Hello, " + name

# Call the function
print(greet("World"))

# Function with multiple parameters
def power(base, exponent):
      return base ** exponent

# Call the function
print(power(2, 3))

### Part 2: Python Data Structures

Python has four basic inbuilt data structures: `Lists`, `Tuples`, `Sets`, and `Dictionaries`.

#### Lists

A list is a collection of items. It is ordered, changeable, and allows duplicate elements.

In [ ]:
# Define a list
fruits = ["apple", "banana", "cherry"]
print(fruits)

# Access list items by index
print(fruits[0])

# Change the value of a list item
fruits[1] = "blueberry"
print(fruits)

# Add an item to the list
fruits.append("orange")
print(fruits)

#### Tuples

A tuple is similar to a list, but it is ordered and unchangeable.


In [ ]:
# Define a tuple
fruits_tuple = ("apple", "banana", "cherry")
print(fruits_tuple)

# Access tuple items by index
print(fruits_tuple[0])

# Trying to change the value of a tuple item throws an error
# fruits_tuple[1] = "blueberry"  # This will throw an error

#### Dictionaries

A dictionary is an unordered collection of key-value pairs.

In [ ]:
# Define a dictionary
fruit_colors = {
    "apple": "red",
    "banana": "yellow",
    "cherry": "red"
}
print(fruit_colors)

In [ ]:
# Access dictionary items by key
print(fruit_colors["apple"])

In [ ]:
# Change the value of a dictionary item
fruit_colors["banana"] = "green"
print(fruit_colors)

#### Sets

A set is an unordered collection of unique items.

In [ ]:
# Define a set
fruits_set = {"apple", "banana", "cherry", "apple"}
print(fruits_set)  # Duplicates are removed


### Part 3: Introduction to Pandas and NumPy

#### Creating arrays in NumPy

In [ ]:
import numpy as np

In [ ]:
# Create a one-dimensional array
a = np.array([1, 2, 3])
print(a)

In [ ]:
# Create a two-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

#### Manipulating arrays in NumPy

In [ ]:
# Change an element of the array
b[0, 0] = 10
print(b)


In [ ]:
# Get the shape of the array
print(a.shape)
print(b.shape)


#### Creating DataFrames in Pandas


In [ ]:
import pandas as pd

# Create a DataFrame from a dictionary
df = pd.DataFrame({
      "Name": ["Alice", "Bob", "Charlie"],
      "Age": [25, 30, 35],
      "Occupation": ["Doctor", "Engineer", "Teacher"]
})
print(df)


#### Manipulating DataFrames in Pandas

In [ ]:
# Select a column
print(df["Name"])


In [ ]:
# Add a new column
df["Salary"] = [100000, 120000, 90000]
print(df)


In [ ]:
# Delete a column
df = df.drop("Age", axis=1)
print(df)

#### Reading data from CSV files


In [ ]:
# Assuming we have a CSV file "data.csv"
df = pd.read_csv("../data/iris/bezdekIris.data")
print(df.head())

**Please note**: you'd need to have a `data.csv` file available and replace `data.csv` with the path to your file. Uncomment this section when ready to use.

#### Basic data exploration


In [ ]:
# Get the shape of the DataFrame
print(df.shape)


In [ ]:
# Get information about the DataFrame
print(df.info())


In [ ]:
# Describe the DataFrame
print(df.describe())


# Introduction to Python for Data Science

## Agenda for Week 3

### Hands-on Workshop: Python for Data Science

1. Basic Python programming skills with a focus on data analysis.
1. Introduction to Python programming language
1. Basic Python syntax and data structures (lists, tuples, dictionaries)
1. Introduction to Python libraries for data science (Pandas, Numpy)
1. Reading data into Python and performing basic data cleaning
1. Simple data analysis using Python



## Weekly Meeting Agenda

Each meeting can have its unique structure depending on the nature of the session, but it's useful to have a general framework to ensure meetings are well-organized and efficient.

1. **Introduction** (5-10 minutes):
   - Welcome participants.
   - Share the agenda for the meeting.
   - Recap the last meeting (if applicable) and note any follow-ups.

2. **Main Agenda** (40-45 minutes):
   - This is where the main activities of the meeting will take place.
   - For a **workshop** or **lecture**, this will include the main presentation and demonstration.
   - For a **discussion**, this may involve presenting the topic and then facilitating a group discussion.
   - For a **hackathon** or **project showcase**, this would include the actual work or presentations.

3. **Q&A/Discussion** (5-10 minutes):
   - Reserve some time for attendees to ask questions or discuss the day's topic further.
   - Encourage participation and interaction.

4. **Conclusion and Looking Ahead** (2-3 minutes):
   - Wrap up the meeting and summarize key points.
   - Briefly mention what the next meeting will entail.
   - Thank everyone for their participation.

This is a very flexible structure and can be adjusted to better suit the type and purpose of each meeting.

## Part 1: Python Basics

### Variables and Data Types

In Python, we can store information in variables. There are several types of data we can store, including integers, floating point numbers, strings, and Booleans.


In [73]:
# Float
y = 10.0
print(type(y))


<class 'float'>


In [75]:
# Boolean
a = True
print(type(a))


<class 'bool'>


In [76]:
# Addition
print(5 + 5)

10


In [78]:
# Multiplication
print(3 * 3)


9


In [80]:
# Exponentiation
print(4 ** 2)

16


#### Logical Operations

Python also supports logical operations, which are often used in conditional statements.

In [82]:
# Or operation
print(True or False)


True


#### Conditional Statements

Conditional statements are used to perform different computations or actions depending on whether a condition evaluates to true or false.

In [85]:
# If-else statement
if x % 2 == 0:
    print("x is even")
else:
    print("x is odd")


x is even


#### Loops

Loops are used to repeatedly execute a block of code.


In [88]:
# While loop
i = 0
while i < 5:
    print(i)
    i += 1


0
1
2
3
4


#### Functions

Functions are reusable blocks of code that perform a specific task.

### Part 2: Python Data Structures

Python has four basic inbuilt data structures: `Lists`, `Tuples`, `Sets`, and `Dictionaries`.

In [91]:
# Define a list
fruits = ["apple", "banana", "cherry"]
print(fruits)

# Access list items by index
print(fruits[0])

# Change the value of a list item
fruits[1] = "blueberry"
print(fruits)

# Add an item to the list
fruits.append("orange")
print(fruits)

['apple', 'banana', 'cherry']
apple
['apple', 'blueberry', 'cherry']
['apple', 'blueberry', 'cherry', 'orange']


In [92]:
# Define a tuple
fruits_tuple = ("apple", "banana", "cherry")
print(fruits_tuple)

# Access tuple items by index
print(fruits_tuple[0])

# Trying to change the value of a tuple item throws an error
# fruits_tuple[1] = "blueberry"  # This will throw an error

('apple', 'banana', 'cherry')
apple


In [93]:
# Define a dictionary
fruit_colors = {
    "apple": "red",
    "banana": "yellow",
    "cherry": "red"
}
print(fruit_colors)

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}


In [95]:
# Change the value of a dictionary item
fruit_colors["banana"] = "green"
print(fruit_colors)

{'apple': 'red', 'banana': 'green', 'cherry': 'red'}


In [96]:
# Define a set
fruits_set = {"apple", "banana", "cherry", "apple"}
print(fruits_set)  # Duplicates are removed


{'banana', 'apple', 'cherry'}


In [97]:
import numpy as np

In [99]:
# Create a two-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [100]:
# Change an element of the array
b[0, 0] = 10
print(b)


[[10  2  3]
 [ 4  5  6]]


#### Creating DataFrames in Pandas


#### Manipulating DataFrames in Pandas

In [104]:
# Add a new column
df["Salary"] = [100000, 120000, 90000]
print(df)


      Name  Age Occupation  Salary
0    Alice   25     Doctor  100000
1      Bob   30   Engineer  120000
2  Charlie   35    Teacher   90000


#### Reading data from CSV files


**Please note**: you'd need to have a `data.csv` file available and replace `data.csv` with the path to your file. Uncomment this section when ready to use.

In [111]:
# Get the shape of the DataFrame
print(df.shape)


(149, 5)


In [113]:
# Describe the DataFrame
print(df.describe())


              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.054362    3.773826    1.206040
std      0.828594    0.435810    1.760543    0.760354
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000
